name: Continuous Deployment

on:
  push:
    branches:
      - main

jobs:
  deployment:
    runs-on: self-hosted
    steps:
      - name: Checkout main branch
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: "14.x"

      - name: Setup yarn
        run: npm install -g yarn

      - name: Setup Nodejs with yarn caching
        uses: actions/setup-node@v2
        with:
          node-version: "14.x"
          cache: yarn

      - name: Install dependencies
        run: yarn

      - name: Build solution
        run: |
          yarn build

      - name: Restart server application
        run: |
          pm2 restart blog || pm2 start yarn --name "blog" -- start
