name: Continuous Deployment

on:
  push:
    branches:
      - main

jobs:
  deployment:
    runs-on: self-hosted
    steps:
      - name: Checkout main branch
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: "14.x"

      - name: Install dependencies
        run: npm ci

      - name: Build solution
        run: npm run build

      - name: Restart server application
        run: |
          pm2 delete blog || true 
          pm2 start npm --name "blog" -- start
